FROM python:3.9

WORKDIR /app

COPY requirements.txt ./

RUN pip install --no-cache-dir --upgrade -r requirements.txt

COPY . .

EXPOSE 8001

ENV POST_STATS_SERVICE_URL="http://0.0.0.0:8003/post-stats"
ENV POST_COMMENTS_SERVICE_URL="http://0.0.0.0:8002/post-comments"

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8001"]

